name: Cypress Tests

on:
  push:
    branches:
      - main
      - pipeline
  pull_request:
    branches:
      - main
      - pipeline
      
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          CYPRESS_USERNAME: ${{secrets.CYPRESS_USERNAME}}
          CYPRESS_PASSWORD: ${{secrets.CYPRESS_PASSWORD}}
        run: npm run cy:run

      - name: Generate cypress reports
        run: npm run report:generate
        
      - name: Upload Cypress reports
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: reports

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore